name: Update Gitfolio Portfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print environment variables
      run: |
        echo "GH_TOKEN=$GH_TOKEN"
        env

    - name: Check Git configuration
      run: |
        git config --list

    - name: Print repository information
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"

    - name: Create test file for pushing
      run: |
        echo "Test file created at $(date)" > test-file.txt
        git add test-file.txt
        git commit -m "Add test file"
        git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

    - name: Generate Gitfolio Portfolio
      run: |
        # Commands to generate the portfolio (e.g., npm install, build, etc.)
    
    - name: Commit and Push changes
      run: |
        git add .
        git commit -m "Update Gitfolio portfolio"
        git push https://${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
