name: Build and Deploy Gitfolio

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Pull the latest changes from the repository
      - name: Pull latest changes
        run: |
          git fetch origin
          git reset --hard origin/main  # Replace 'main' with your default branch

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install gitfolio -g

      # Step 4: Generate Gitfolio Portfolio
      - name: Generate Gitfolio Portfolio
        run: gitfolio update

      # Step 5: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update Gitfolio portfolio" || echo "No changes to commit"
          git push origin main


      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with the directory containing generated files
